# Generated by Django 4.1.5 on 2023-01-07 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('ClubID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MemberCount', models.IntegerField(default=1)),
                ('streetNo', models.TextField()),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('postcode', models.TextField()),
                ('landlineNo', models.TextField()),
                ('mobileNo', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accessLevel', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Representitive',
            fields=[
                ('clubRepID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.clubs')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.users')),
            ],
        ),
    ]
