# Generated by Django 4.1.5 on 2023-01-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
