# Generated by Django 4.1.5 on 2023-01-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_clubs_club_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='representitive',
            name='clubID',
        ),
        migrations.RemoveField(
            model_name='representitive',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Representitive',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
