# Generated by Django 4.1.5 on 2023-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='employee',
            name='lastName',
            field=models.CharField(default='Bob', max_length=200),
            preserve_default=False,
        ),
    ]
