# Generated by Django 4.1.5 on 2023-01-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_club_clubname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DateOfBirth',
            new_name='dateOfBirth',
        ),
    ]
