# Generated by Django 4.1.5 on 2023-01-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_rename_dateofbirth_user_dateofbirth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='MemberCount',
            new_name='memberCount',
        ),
    ]
