# Generated by Django 4.1.5 on 2023-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='landlineNo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='mobileNo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='postcode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='streetNo',
            field=models.CharField(max_length=200),
        ),
    ]
