# Generated by Django 4.1.5 on 2023-01-14 00:57

import Accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_rename_clubid_representitive_affiliatedclub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cardHolderName',
            field=models.CharField(default='Card holder name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cardNumber',
            field=models.CharField(default=1234567890123456, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cvv',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expirationDate',
            field=models.DateField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='clubName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='landlineNo',
            field=models.CharField(max_length=255, null=True, validators=[Accounts.models.isLandlineNumber]),
        ),
        migrations.AlterField(
            model_name='club',
            name='postcode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manager',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='representitive',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
