# Generated by Django 4.1.5 on 2023-01-14 01:46

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_user_cardholdername_user_cardnumber_user_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cardHolderName',
            field=models.CharField(max_length=255, validators=[Accounts.models.validate_cardholder_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cardNumber',
            field=models.CharField(max_length=16, validators=[Accounts.models.validateCardNumber]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cvv',
            field=models.CharField(max_length=4, validators=[Accounts.models.validate_cvv]),
        ),
        migrations.AlterField(
            model_name='user',
            name='expirationDate',
            field=models.CharField(max_length=5),
        ),
    ]
