# Generated by Django 4.1.5 on 2023-01-14 02:34

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_user_cardholdername_alter_user_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirationDate',
            field=models.CharField(max_length=5, validators=[Accounts.models.validateExpirationDate]),
        ),
    ]
