# Generated by Django 4.1.5 on 2023-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_clubpurchasehistory_date_userpurchasehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpurchasehistory',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpurchasehistory',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
